language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8


script:
    - make clean
    - GCC=gcc-8 CFLAGS=-O1 make check-gcc  # fortify_source already active
    - make dist
